//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GheskioCovid19.Models
{
    using System;
    using System.Collections.Generic;

    public partial class V_ENTETE_VISITE_COVID
    {
        public string SITE_ID { get; set; }
        public string SIGLE_SITE { get; set; }
        public string SITE_DESC { get; set; }
        public string PAT_NET_ID { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> MOIS_ENTRY { get; set; }
        public Nullable<System.DateTime> DOB_DATE { get; set; }
        public string GHESKIO_ID { get; set; }
        public Nullable<short> COUNTER { get; set; }
        public string ADRESS { get; set; }
        public string CELPHONE { get; set; }
        public string CELPHONE2 { get; set; }
        public string HOUSETEL { get; set; }
        public string HOUSETEL2 { get; set; }
        public System.DateTime ENROL_DATE { get; set; }
        public string GENDER_DESC { get; set; }
        public Nullable<int> CURRENT_AGE { get; set; }
    }
}


